language: java
jdk:
- oraclejdk8
install: true
script:
  - ./.ci/ci.sh
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr plugin-maven/localMavenRepository/com/diffplug/spotless/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - plugin-maven/localMavenRepository
